insert into book (title, `desc`, cover_image) values ('Two Days, One Night (Deux jours, une nuit)', 'target customized supply-chains', 'http://dummyimage.com/165x100.png/ff4444/ffffff');
insert into book (title, `desc`, cover_image) values ('Auschwitz: The Nazis and the ''Final Solution''', 'exploit mission-critical technologies', 'http://dummyimage.com/200x100.png/cc0000/ffffff');
insert into book (title, `desc`, cover_image) values ('Django, Kill... If You Live, Shoot! (Se sei vivo spara)', 'recontextualize plug-and-play architectures', 'http://dummyimage.com/216x100.png/ff4444/ffffff');
insert into book (title, `desc`, cover_image) values ('Black Swan', 'iterate granular niches', 'http://dummyimage.com/106x100.png/dddddd/000000');
insert into book (title, `desc`, cover_image) values ('This Sporting Life', 'maximize holistic bandwidth', 'http://dummyimage.com/101x100.png/ff4444/ffffff');
insert into book (title, `desc`, cover_image) values ('Mackenna''s Gold', 'recontextualize bricks-and-clicks synergies', 'http://dummyimage.com/148x100.png/ff4444/ffffff');
insert into book (title, `desc`, cover_image) values ('CJ7 (Cheung Gong 7 hou)', 'mesh cutting-edge systems', 'http://dummyimage.com/148x100.png/ff4444/ffffff');
insert into book (title, `desc`, cover_image) values ('Sarafina!', 'monetize 24/7 niches', 'http://dummyimage.com/106x100.png/cc0000/ffffff');
insert into book (title, `desc`, cover_image) values ('Dungeons & Dragons', 'mesh strategic initiatives', 'http://dummyimage.com/219x100.png/cc0000/ffffff');
insert into book (title, `desc`, cover_image) values ('Lara Croft Tomb Raider: The Cradle of Life', 'redefine cutting-edge mindshare', 'http://dummyimage.com/115x100.png/5fa2dd/ffffff');
insert into book (title, `desc`, cover_image) values ('3 Idiots', 'harness rich portals', 'http://dummyimage.com/112x100.png/ff4444/ffffff');
insert into book (title, `desc`, cover_image) values ('Harem suare', 'revolutionize web-enabled experiences', 'http://dummyimage.com/180x100.png/dddddd/000000');
insert into book (title, `desc`, cover_image) values ('People That Time Forgot, The', 'exploit magnetic architectures', 'http://dummyimage.com/245x100.png/cc0000/ffffff');
insert into book (title, `desc`, cover_image) values ('Man Apart, A', 'morph web-enabled e-markets', 'http://dummyimage.com/105x100.png/5fa2dd/ffffff');
insert into book (title, `desc`, cover_image) values ('Love in Bloom', 'brand extensible synergies', 'http://dummyimage.com/145x100.png/5fa2dd/ffffff');
insert into book (title, `desc`, cover_image) values ('Chairman of the Board', 'embrace ubiquitous experiences', 'http://dummyimage.com/242x100.png/cc0000/ffffff');
insert into book (title, `desc`, cover_image) values ('Good Morning (Ohayô)', 'incubate killer users', 'http://dummyimage.com/175x100.png/cc0000/ffffff');
insert into book (title, `desc`, cover_image) values ('Our Family Wedding', 'monetize robust infomediaries', 'http://dummyimage.com/113x100.png/dddddd/000000');
insert into book (title, `desc`, cover_image) values ('Starman', 'e-enable seamless convergence', 'http://dummyimage.com/149x100.png/cc0000/ffffff');
insert into book (title, `desc`, cover_image) values ('Sebastian Maniscalco: What''s Wrong with People?', 'enhance customized networks', 'http://dummyimage.com/220x100.png/cc0000/ffffff');
insert into book (title, `desc`, cover_image) values ('Hellsing Ultimate OVA Series', 'envisioneer open-source methodologies', 'http://dummyimage.com/228x100.png/dddddd/000000');
insert into book (title, `desc`, cover_image) values ('Summer by the River, A (Kuningasjätkä)', 'target customized content', 'http://dummyimage.com/192x100.png/dddddd/000000');
insert into book (title, `desc`, cover_image) values ('Claustrofobia', 'revolutionize intuitive web services', 'http://dummyimage.com/111x100.png/dddddd/000000');
insert into book (title, `desc`, cover_image) values ('Little Italy', 'empower holistic solutions', 'http://dummyimage.com/234x100.png/dddddd/000000');
insert into book (title, `desc`, cover_image) values ('Control', 'evolve bleeding-edge methodologies', 'http://dummyimage.com/219x100.png/dddddd/000000');
insert into book (title, `desc`, cover_image) values ('Evil Remains (Trespassing)', 'cultivate B2C web-readiness', 'http://dummyimage.com/104x100.png/cc0000/ffffff');
insert into book (title, `desc`, cover_image) values ('Heights', 'utilize customized models', 'http://dummyimage.com/171x100.png/ff4444/ffffff');
insert into book (title, `desc`, cover_image) values ('Taxi to the Dark Side', 'brand web-enabled markets', 'http://dummyimage.com/182x100.png/cc0000/ffffff');
insert into book (title, `desc`, cover_image) values ('What Dreams May Come', 'iterate magnetic experiences', 'http://dummyimage.com/165x100.png/dddddd/000000');
insert into book (title, `desc`, cover_image) values ('Dona Flor and Her Two Husbands (Dona Flor e Seus Dois Maridos)', 'maximize wireless interfaces', 'http://dummyimage.com/215x100.png/dddddd/000000');
insert into book (title, `desc`, cover_image) values ('Gravity (Schwerkraft)', 'target innovative systems', 'http://dummyimage.com/192x100.png/dddddd/000000');
insert into book (title, `desc`, cover_image) values ('Favor', 'expedite bleeding-edge bandwidth', 'http://dummyimage.com/167x100.png/ff4444/ffffff');
insert into book (title, `desc`, cover_image) values ('Hen Hop', 'expedite dot-com solutions', 'http://dummyimage.com/135x100.png/5fa2dd/ffffff');
insert into book (title, `desc`, cover_image) values ('Claire of the Moon', 'embrace ubiquitous relationships', 'http://dummyimage.com/250x100.png/ff4444/ffffff');
insert into book (title, `desc`, cover_image) values ('Crime and Punishment', 'transform wireless interfaces', 'http://dummyimage.com/120x100.png/5fa2dd/ffffff');
insert into book (title, `desc`, cover_image) values ('Flesh & Blood', 'unleash back-end portals', 'http://dummyimage.com/231x100.png/dddddd/000000');
insert into book (title, `desc`, cover_image) values ('Compulsion', 'cultivate compelling eyeballs', 'http://dummyimage.com/210x100.png/5fa2dd/ffffff');
insert into book (title, `desc`, cover_image) values ('History of Postwar Japan as Told by a Bar Hostess (Nippon Sengoshi - Madamu onboro no Seikatsu)', 'leverage dot-com e-commerce', 'http://dummyimage.com/160x100.png/cc0000/ffffff');
insert into book (title, `desc`, cover_image) values ('Crazy Thunder Road', 'repurpose proactive platforms', 'http://dummyimage.com/131x100.png/5fa2dd/ffffff');
insert into book (title, `desc`, cover_image) values ('Masquerade (Gwanghai, Wangyidoen namja)', 'cultivate B2C e-tailers', 'http://dummyimage.com/114x100.png/cc0000/ffffff');
insert into book (title, `desc`, cover_image) values ('Dark Dungeons', 'visualize innovative communities', 'http://dummyimage.com/128x100.png/ff4444/ffffff');
insert into book (title, `desc`, cover_image) values ('Two Moon Junction', 'mesh holistic infomediaries', 'http://dummyimage.com/124x100.png/cc0000/ffffff');
insert into book (title, `desc`, cover_image) values ('Reservation Road', 'enable cross-media e-business', 'http://dummyimage.com/237x100.png/5fa2dd/ffffff');
insert into book (title, `desc`, cover_image) values ('Enola Gay and the Atomic Bombing of Japan', 'deploy 24/365 bandwidth', 'http://dummyimage.com/146x100.png/ff4444/ffffff');
insert into book (title, `desc`, cover_image) values ('Last Rites of Joe May, The', 'utilize visionary experiences', 'http://dummyimage.com/195x100.png/5fa2dd/ffffff');
insert into book (title, `desc`, cover_image) values ('Steve Jobs: The Lost Interview', 'deliver seamless e-business', 'http://dummyimage.com/165x100.png/5fa2dd/ffffff');
insert into book (title, `desc`, cover_image) values ('Bouncing Babies', 'transition wireless eyeballs', 'http://dummyimage.com/101x100.png/ff4444/ffffff');
insert into book (title, `desc`, cover_image) values ('Minion, The', 'mesh sexy communities', 'http://dummyimage.com/145x100.png/dddddd/000000');
insert into book (title, `desc`, cover_image) values ('Die Is Cast, The (La suerte está echada)', 'morph interactive e-business', 'http://dummyimage.com/107x100.png/cc0000/ffffff');
insert into book (title, `desc`, cover_image) values ('New Best Friend', 'deliver strategic functionalities', 'http://dummyimage.com/168x100.png/cc0000/ffffff');
insert into book (title, `desc`, cover_image) values ('Hallelujah I''m a Bum', 'drive 24/365 synergies', 'http://dummyimage.com/155x100.png/ff4444/ffffff');
insert into book (title, `desc`, cover_image) values ('Horrors of Spider Island (Ein Toter Hing im Netz)', 'engage enterprise platforms', 'http://dummyimage.com/200x100.png/cc0000/ffffff');
insert into book (title, `desc`, cover_image) values ('Our Town', 'expedite real-time systems', 'http://dummyimage.com/125x100.png/cc0000/ffffff');
insert into book (title, `desc`, cover_image) values ('Prize Winner of Defiance Ohio, The', 'enable seamless eyeballs', 'http://dummyimage.com/100x100.png/5fa2dd/ffffff');
insert into book (title, `desc`, cover_image) values ('I Am Waiting (Ore wa matteru ze)', 'generate leading-edge infomediaries', 'http://dummyimage.com/141x100.png/ff4444/ffffff');
insert into book (title, `desc`, cover_image) values ('Remarkable Power', 'optimize strategic convergence', 'http://dummyimage.com/115x100.png/ff4444/ffffff');
insert into book (title, `desc`, cover_image) values ('Kummelin jackpot', 'target killer functionalities', 'http://dummyimage.com/144x100.png/dddddd/000000');
insert into book (title, `desc`, cover_image) values ('RocketMan (a.k.a. Rocket Man)', 'mesh interactive bandwidth', 'http://dummyimage.com/202x100.png/5fa2dd/ffffff');
insert into book (title, `desc`, cover_image) values ('Up the Yangtze', 'embrace e-business mindshare', 'http://dummyimage.com/209x100.png/5fa2dd/ffffff');
insert into book (title, `desc`, cover_image) values ('Zero de conduite (Zero for Conduct) (Zéro de conduite: Jeunes diables au collège)', 'scale web-enabled deliverables', 'http://dummyimage.com/174x100.png/5fa2dd/ffffff');
insert into book (title, `desc`, cover_image) values ('High Cost of Living, The', 'evolve end-to-end content', 'http://dummyimage.com/138x100.png/dddddd/000000');
insert into book (title, `desc`, cover_image) values ('Company', 'revolutionize synergistic convergence', 'http://dummyimage.com/152x100.png/ff4444/ffffff');
insert into book (title, `desc`, cover_image) values ('Reach the Rock', 'seize rich content', 'http://dummyimage.com/182x100.png/ff4444/ffffff');
insert into book (title, `desc`, cover_image) values ('The Time Being', 'orchestrate plug-and-play metrics', 'http://dummyimage.com/219x100.png/dddddd/000000');
insert into book (title, `desc`, cover_image) values ('Devil''s Playground', 'engineer holistic bandwidth', 'http://dummyimage.com/115x100.png/5fa2dd/ffffff');
insert into book (title, `desc`, cover_image) values ('My Beautiful Laundrette', 'extend real-time mindshare', 'http://dummyimage.com/174x100.png/5fa2dd/ffffff');
insert into book (title, `desc`, cover_image) values ('Save the Green Planet! (Jigureul jikyeora!)', 'transition visionary functionalities', 'http://dummyimage.com/125x100.png/ff4444/ffffff');
insert into book (title, `desc`, cover_image) values ('King Solomon''s Mines', 'e-enable visionary deliverables', 'http://dummyimage.com/185x100.png/5fa2dd/ffffff');
insert into book (title, `desc`, cover_image) values ('Wanted', 'drive cross-platform communities', 'http://dummyimage.com/193x100.png/dddddd/000000');
insert into book (title, `desc`, cover_image) values ('Great Stone Face, The', 'deploy web-enabled models', 'http://dummyimage.com/225x100.png/cc0000/ffffff');
insert into book (title, `desc`, cover_image) values ('Casanova', 'empower out-of-the-box networks', 'http://dummyimage.com/158x100.png/ff4444/ffffff');
insert into book (title, `desc`, cover_image) values ('Remember My Name', 'mesh transparent web-readiness', 'http://dummyimage.com/184x100.png/5fa2dd/ffffff');
insert into book (title, `desc`, cover_image) values ('End of America, The', 'unleash wireless e-commerce', 'http://dummyimage.com/228x100.png/ff4444/ffffff');
insert into book (title, `desc`, cover_image) values ('Crystal Fairy & the Magical Cactus and 2012', 'embrace cross-platform platforms', 'http://dummyimage.com/238x100.png/cc0000/ffffff');
insert into book (title, `desc`, cover_image) values ('Little Witches', 'orchestrate front-end e-tailers', 'http://dummyimage.com/109x100.png/5fa2dd/ffffff');
insert into book (title, `desc`, cover_image) values ('Hellraiser: Deader', 'empower end-to-end e-services', 'http://dummyimage.com/113x100.png/ff4444/ffffff');
insert into book (title, `desc`, cover_image) values ('The Scapegoat', 'morph one-to-one solutions', 'http://dummyimage.com/107x100.png/ff4444/ffffff');
insert into book (title, `desc`, cover_image) values ('Snapshot', 'seize scalable convergence', 'http://dummyimage.com/181x100.png/cc0000/ffffff');
insert into book (title, `desc`, cover_image) values ('Valentine''s Day', 'monetize frictionless mindshare', 'http://dummyimage.com/130x100.png/ff4444/ffffff');
insert into book (title, `desc`, cover_image) values ('One A.M.', 'reinvent 24/7 e-tailers', 'http://dummyimage.com/136x100.png/5fa2dd/ffffff');
insert into book (title, `desc`, cover_image) values ('Ride with the Devil', 'syndicate integrated interfaces', 'http://dummyimage.com/200x100.png/ff4444/ffffff');
insert into book (title, `desc`, cover_image) values ('Salvage', 'morph world-class content', 'http://dummyimage.com/126x100.png/5fa2dd/ffffff');
insert into book (title, `desc`, cover_image) values ('Pink Floyd: The Wall', 'transition ubiquitous relationships', 'http://dummyimage.com/129x100.png/cc0000/ffffff');
insert into book (title, `desc`, cover_image) values ('Dogville', 'envisioneer wireless models', 'http://dummyimage.com/159x100.png/dddddd/000000');
insert into book (title, `desc`, cover_image) values ('Tale of Ham and Passion, A (Jamón, Jamón)', 'benchmark real-time e-services', 'http://dummyimage.com/125x100.png/dddddd/000000');
insert into book (title, `desc`, cover_image) values ('Truth About Charlie, The', 'exploit bricks-and-clicks communities', 'http://dummyimage.com/151x100.png/5fa2dd/ffffff');
insert into book (title, `desc`, cover_image) values ('Loner (Woetoli)', 'unleash dot-com platforms', 'http://dummyimage.com/182x100.png/ff4444/ffffff');
insert into book (title, `desc`, cover_image) values ('Piripäiväkirja', 'incentivize open-source systems', 'http://dummyimage.com/180x100.png/ff4444/ffffff');
insert into book (title, `desc`, cover_image) values ('Sessions, The (Surrogate, The)', 'recontextualize leading-edge metrics', 'http://dummyimage.com/213x100.png/dddddd/000000');
insert into book (title, `desc`, cover_image) values ('Punishment Park', 'leverage holistic channels', 'http://dummyimage.com/114x100.png/dddddd/000000');
insert into book (title, `desc`, cover_image) values ('Convent, The', 'productize next-generation schemas', 'http://dummyimage.com/237x100.png/5fa2dd/ffffff');
insert into book (title, `desc`, cover_image) values ('Chinese Coffee', 'harness cross-platform e-business', 'http://dummyimage.com/194x100.png/cc0000/ffffff');
insert into book (title, `desc`, cover_image) values ('Voices of a Distant Star (Hoshi no koe)', 'empower scalable portals', 'http://dummyimage.com/121x100.png/cc0000/ffffff');
insert into book (title, `desc`, cover_image) values ('Desert of Forbidden Art, The', 'maximize virtual initiatives', 'http://dummyimage.com/177x100.png/cc0000/ffffff');
insert into book (title, `desc`, cover_image) values ('Black Snake Moan', 'optimize best-of-breed e-services', 'http://dummyimage.com/173x100.png/dddddd/000000');
insert into book (title, `desc`, cover_image) values ('Closer to the Moon', 'reintermediate one-to-one bandwidth', 'http://dummyimage.com/205x100.png/5fa2dd/ffffff');
insert into book (title, `desc`, cover_image) values ('Two Rode Together', 'orchestrate viral e-business', 'http://dummyimage.com/113x100.png/5fa2dd/ffffff');
insert into book (title, `desc`, cover_image) values ('Fame', 'deploy best-of-breed niches', 'http://dummyimage.com/167x100.png/5fa2dd/ffffff');
insert into book (title, `desc`, cover_image) values ('Journey to the Far Side of the Sun (a.k.a. Doppelgänger)', 'orchestrate value-added technologies', 'http://dummyimage.com/162x100.png/5fa2dd/ffffff');
insert into book (title, `desc`, cover_image) values ('A.I. Artificial Intelligence', 'integrate value-added synergies', 'http://dummyimage.com/108x100.png/5fa2dd/ffffff');
insert into book (title, `desc`, cover_image) values ('Matthew''s Days', 'grow value-added platforms', 'http://dummyimage.com/229x100.png/ff4444/ffffff');
insert into book (title, `desc`, cover_image) values ('Spanglish', 'brand mission-critical technologies', 'http://dummyimage.com/235x100.png/cc0000/ffffff');
insert into book (title, `desc`, cover_image) values ('Chapiteau-show (Shapito-shou)', 'target real-time interfaces', 'http://dummyimage.com/101x100.png/dddddd/000000');
insert into book (title, `desc`, cover_image) values ('Grace', 'repurpose turn-key applications', 'http://dummyimage.com/152x100.png/cc0000/ffffff');
insert into book (title, `desc`, cover_image) values ('Trial by Jury', 'transform killer ROI', 'http://dummyimage.com/111x100.png/cc0000/ffffff');
insert into book (title, `desc`, cover_image) values ('Smashing Pumpkins: If All Goes Wrong', 'revolutionize bleeding-edge schemas', 'http://dummyimage.com/160x100.png/ff4444/ffffff');
insert into book (title, `desc`, cover_image) values ('Hunger', 'deploy holistic markets', 'http://dummyimage.com/193x100.png/5fa2dd/ffffff');
insert into book (title, `desc`, cover_image) values ('Splinterheads', 'mesh holistic ROI', 'http://dummyimage.com/170x100.png/ff4444/ffffff');
insert into book (title, `desc`, cover_image) values ('Dead or Alive: Hanzaisha', 'transform seamless partnerships', 'http://dummyimage.com/200x100.png/dddddd/000000');
insert into book (title, `desc`, cover_image) values ('Little Women', 'benchmark efficient e-services', 'http://dummyimage.com/247x100.png/cc0000/ffffff');
insert into book (title, `desc`, cover_image) values ('Antonia''s Line (Antonia)', 'extend dynamic web-readiness', 'http://dummyimage.com/152x100.png/dddddd/000000');
insert into book (title, `desc`, cover_image) values ('Legend', 'productize granular vortals', 'http://dummyimage.com/212x100.png/cc0000/ffffff');
insert into book (title, `desc`, cover_image) values ('Dangerous Corner', 'seize integrated convergence', 'http://dummyimage.com/143x100.png/ff4444/ffffff');
insert into book (title, `desc`, cover_image) values ('Life Apart: Hasidism in America, A', 'optimize global platforms', 'http://dummyimage.com/149x100.png/5fa2dd/ffffff');
insert into book (title, `desc`, cover_image) values ('Supervixens', 'benchmark global e-services', 'http://dummyimage.com/140x100.png/dddddd/000000');
insert into book (title, `desc`, cover_image) values ('Ishtar', 'orchestrate frictionless networks', 'http://dummyimage.com/161x100.png/dddddd/000000');
insert into book (title, `desc`, cover_image) values ('Living with Michael Jackson', 'orchestrate enterprise e-business', 'http://dummyimage.com/111x100.png/cc0000/ffffff');
insert into book (title, `desc`, cover_image) values ('Diario de un skin', 'productize open-source channels', 'http://dummyimage.com/112x100.png/5fa2dd/ffffff');
insert into book (title, `desc`, cover_image) values ('The Inspector', 'maximize collaborative synergies', 'http://dummyimage.com/210x100.png/cc0000/ffffff');
insert into book (title, `desc`, cover_image) values ('Mercy', 'monetize turn-key convergence', 'http://dummyimage.com/250x100.png/cc0000/ffffff');
insert into book (title, `desc`, cover_image) values ('Truly Human (Et rigtigt menneske)', 'reinvent cross-media applications', 'http://dummyimage.com/136x100.png/5fa2dd/ffffff');
insert into book (title, `desc`, cover_image) values ('Vacancy 2: The First Cut', 'benchmark web-enabled infomediaries', 'http://dummyimage.com/170x100.png/dddddd/000000');
insert into book (title, `desc`, cover_image) values ('Border Incident', 'implement dot-com interfaces', 'http://dummyimage.com/246x100.png/cc0000/ffffff');
insert into book (title, `desc`, cover_image) values ('Jalla! Jalla!', 'iterate vertical convergence', 'http://dummyimage.com/111x100.png/ff4444/ffffff');
insert into book (title, `desc`, cover_image) values ('Memory of a Killer, The (Zaak Alzheimer, De)', 'innovate bricks-and-clicks models', 'http://dummyimage.com/160x100.png/5fa2dd/ffffff');
insert into book (title, `desc`, cover_image) values ('Love Punch, The', 'empower holistic e-business', 'http://dummyimage.com/134x100.png/ff4444/ffffff');
insert into book (title, `desc`, cover_image) values ('Promised Land', 'reinvent intuitive partnerships', 'http://dummyimage.com/177x100.png/5fa2dd/ffffff');
insert into book (title, `desc`, cover_image) values ('My Flesh and Blood', 'reinvent user-centric bandwidth', 'http://dummyimage.com/147x100.png/5fa2dd/ffffff');
insert into book (title, `desc`, cover_image) values ('Barber of Siberia, The (Sibirskij tsiryulnik)', 'syndicate cutting-edge metrics', 'http://dummyimage.com/144x100.png/ff4444/ffffff');
insert into book (title, `desc`, cover_image) values ('ABCs of Death, The', 'transform next-generation ROI', 'http://dummyimage.com/191x100.png/dddddd/000000');
insert into book (title, `desc`, cover_image) values ('K.G. (Karate Girl)', 'incubate virtual markets', 'http://dummyimage.com/189x100.png/cc0000/ffffff');
insert into book (title, `desc`, cover_image) values ('Warriors of Heaven and Earth (Tian di ying xiong)', 'expedite compelling e-commerce', 'http://dummyimage.com/170x100.png/5fa2dd/ffffff');
insert into book (title, `desc`, cover_image) values ('23 Paces to Baker Street', 'incubate vertical e-business', 'http://dummyimage.com/171x100.png/5fa2dd/ffffff');
insert into book (title, `desc`, cover_image) values ('Grandfather, The (Abuelo, El)', 'implement robust networks', 'http://dummyimage.com/158x100.png/dddddd/000000');
insert into book (title, `desc`, cover_image) values ('Now You See Me', 'benchmark ubiquitous initiatives', 'http://dummyimage.com/125x100.png/cc0000/ffffff');
insert into book (title, `desc`, cover_image) values ('Seabiscuit', 'exploit seamless systems', 'http://dummyimage.com/150x100.png/ff4444/ffffff');
insert into book (title, `desc`, cover_image) values ('How I Ended This Summer (Kak ya provyol etim letom)', 'envisioneer efficient web services', 'http://dummyimage.com/133x100.png/cc0000/ffffff');
insert into book (title, `desc`, cover_image) values ('Presidentintekijät', 'syndicate collaborative networks', 'http://dummyimage.com/121x100.png/ff4444/ffffff');
insert into book (title, `desc`, cover_image) values ('Tarzan', 'innovate scalable ROI', 'http://dummyimage.com/236x100.png/ff4444/ffffff');
insert into book (title, `desc`, cover_image) values ('Pussy Riot: A Punk Prayer', 'disintermediate scalable e-commerce', 'http://dummyimage.com/197x100.png/5fa2dd/ffffff');
insert into book (title, `desc`, cover_image) values ('Extraordinary Stories (Historias extraordinarias)', 'unleash one-to-one e-business', 'http://dummyimage.com/188x100.png/dddddd/000000');
insert into book (title, `desc`, cover_image) values ('Reefer Madness (a.k.a. Tell Your Children)', 'reintermediate proactive paradigms', 'http://dummyimage.com/185x100.png/dddddd/000000');
insert into book (title, `desc`, cover_image) values ('Dukes of Hazzard, The', 'redefine front-end schemas', 'http://dummyimage.com/222x100.png/ff4444/ffffff');
insert into book (title, `desc`, cover_image) values ('Novocaine', 'transform cross-media web services', 'http://dummyimage.com/238x100.png/ff4444/ffffff');
insert into book (title, `desc`, cover_image) values ('3 Needles', 'enable visionary architectures', 'http://dummyimage.com/132x100.png/5fa2dd/ffffff');
insert into book (title, `desc`, cover_image) values ('World''s Greatest Lover, The', 'target clicks-and-mortar convergence', 'http://dummyimage.com/225x100.png/dddddd/000000');
insert into book (title, `desc`, cover_image) values ('Mists of Avalon, The', 'e-enable out-of-the-box e-commerce', 'http://dummyimage.com/134x100.png/ff4444/ffffff');
insert into book (title, `desc`, cover_image) values ('30 Minutes or Less', 'architect visionary e-markets', 'http://dummyimage.com/241x100.png/dddddd/000000');
insert into book (title, `desc`, cover_image) values ('Frankenstein and the Monster from Hell', 'utilize web-enabled users', 'http://dummyimage.com/114x100.png/dddddd/000000');
insert into book (title, `desc`, cover_image) values ('12 Rounds', 'mesh dot-com infomediaries', 'http://dummyimage.com/158x100.png/dddddd/000000');
insert into book (title, `desc`, cover_image) values ('Made of Honor', 'morph cross-platform experiences', 'http://dummyimage.com/147x100.png/5fa2dd/ffffff');
insert into book (title, `desc`, cover_image) values ('Hell''s Angels', 'redefine ubiquitous applications', 'http://dummyimage.com/112x100.png/cc0000/ffffff');
insert into book (title, `desc`, cover_image) values ('Ironclad 2: Battle for Blood', 'repurpose ubiquitous schemas', 'http://dummyimage.com/218x100.png/5fa2dd/ffffff');
insert into book (title, `desc`, cover_image) values ('Dana Carvey: Squatting Monkeys Tell No Lies', 'strategize seamless channels', 'http://dummyimage.com/220x100.png/5fa2dd/ffffff');
insert into book (title, `desc`, cover_image) values ('Wedding Night, The', 'maximize synergistic web-readiness', 'http://dummyimage.com/167x100.png/cc0000/ffffff');
insert into book (title, `desc`, cover_image) values ('Andromeda Strain, The', 'redefine distributed users', 'http://dummyimage.com/120x100.png/5fa2dd/ffffff');
insert into book (title, `desc`, cover_image) values ('Day and Night (Le jour et la nuit)', 'transition integrated relationships', 'http://dummyimage.com/148x100.png/5fa2dd/ffffff');
insert into book (title, `desc`, cover_image) values ('Tale of the Wind, A (Histoire de vent, Une)', 'expedite real-time schemas', 'http://dummyimage.com/244x100.png/cc0000/ffffff');
insert into book (title, `desc`, cover_image) values ('Sahara', 'iterate open-source networks', 'http://dummyimage.com/118x100.png/cc0000/ffffff');
insert into book (title, `desc`, cover_image) values ('Sweet Hearts Dance', 'strategize viral experiences', 'http://dummyimage.com/126x100.png/5fa2dd/ffffff');
insert into book (title, `desc`, cover_image) values ('The Land Before Time V: The Mysterious Island', 'expedite cross-platform convergence', 'http://dummyimage.com/102x100.png/cc0000/ffffff');
insert into book (title, `desc`, cover_image) values ('Skinwalkers', 'reinvent world-class bandwidth', 'http://dummyimage.com/155x100.png/cc0000/ffffff');
insert into book (title, `desc`, cover_image) values ('Taste of Honey, A', 'orchestrate virtual mindshare', 'http://dummyimage.com/212x100.png/ff4444/ffffff');
insert into book (title, `desc`, cover_image) values ('Nine Lives (Ni liv)', 'harness distributed markets', 'http://dummyimage.com/192x100.png/cc0000/ffffff');
insert into book (title, `desc`, cover_image) values ('Animals United', 'drive collaborative models', 'http://dummyimage.com/152x100.png/5fa2dd/ffffff');
insert into book (title, `desc`, cover_image) values ('My Bodyguard', 'engage end-to-end markets', 'http://dummyimage.com/102x100.png/dddddd/000000');
insert into book (title, `desc`, cover_image) values ('Under Siege', 'exploit clicks-and-mortar content', 'http://dummyimage.com/208x100.png/ff4444/ffffff');
insert into book (title, `desc`, cover_image) values ('Beverly Hills Ninja', 'streamline granular synergies', 'http://dummyimage.com/226x100.png/5fa2dd/ffffff');
insert into book (title, `desc`, cover_image) values ('Dream a Little Dream', 'productize synergistic mindshare', 'http://dummyimage.com/146x100.png/dddddd/000000');
insert into book (title, `desc`, cover_image) values ('Proof', 'empower bricks-and-clicks communities', 'http://dummyimage.com/184x100.png/dddddd/000000');
insert into book (title, `desc`, cover_image) values ('Air Doll (Kûki ningyô)', 'integrate real-time vortals', 'http://dummyimage.com/225x100.png/dddddd/000000');
insert into book (title, `desc`, cover_image) values ('Images of the World and the Inscription of War (Bilder der Welt und Inschrift des Krieges)', 'productize efficient networks', 'http://dummyimage.com/145x100.png/cc0000/ffffff');
insert into book (title, `desc`, cover_image) values ('Plastic Age, The', 'embrace frictionless markets', 'http://dummyimage.com/185x100.png/5fa2dd/ffffff');
insert into book (title, `desc`, cover_image) values ('Sleep Tight (Mientras duermes)', 'empower value-added channels', 'http://dummyimage.com/232x100.png/dddddd/000000');
insert into book (title, `desc`, cover_image) values ('Jet Pilot', 'integrate killer action-items', 'http://dummyimage.com/152x100.png/cc0000/ffffff');
insert into book (title, `desc`, cover_image) values ('[REC]²', 'incentivize enterprise architectures', 'http://dummyimage.com/104x100.png/ff4444/ffffff');
insert into book (title, `desc`, cover_image) values ('Junkopia', 'engineer transparent methodologies', 'http://dummyimage.com/129x100.png/5fa2dd/ffffff');
insert into book (title, `desc`, cover_image) values ('A mí las mujeres ni fu ni fa', 'generate plug-and-play e-markets', 'http://dummyimage.com/180x100.png/cc0000/ffffff');
insert into book (title, `desc`, cover_image) values ('Angry Video Game Nerd: The Movie', 'engage turn-key niches', 'http://dummyimage.com/108x100.png/dddddd/000000');
insert into book (title, `desc`, cover_image) values ('King Solomon''s Mines', 'grow granular synergies', 'http://dummyimage.com/225x100.png/ff4444/ffffff');
insert into book (title, `desc`, cover_image) values ('Topo, El', 'aggregate integrated portals', 'http://dummyimage.com/141x100.png/cc0000/ffffff');
insert into book (title, `desc`, cover_image) values ('Zebrahead', 'engage granular portals', 'http://dummyimage.com/225x100.png/ff4444/ffffff');
insert into book (title, `desc`, cover_image) values ('Paparazzi', 'repurpose back-end schemas', 'http://dummyimage.com/230x100.png/5fa2dd/ffffff');
insert into book (title, `desc`, cover_image) values ('Lassie Come Home', 'expedite real-time methodologies', 'http://dummyimage.com/142x100.png/dddddd/000000');
insert into book (title, `desc`, cover_image) values ('From Morn to Midnight (Von morgens bis Mitternacht)', 'expedite end-to-end paradigms', 'http://dummyimage.com/190x100.png/dddddd/000000');
insert into book (title, `desc`, cover_image) values ('Disaster L.A.', 'incubate viral infomediaries', 'http://dummyimage.com/150x100.png/5fa2dd/ffffff');
insert into book (title, `desc`, cover_image) values ('Hong Kong Confidential (Amaya)', 'benchmark impactful functionalities', 'http://dummyimage.com/111x100.png/5fa2dd/ffffff');
insert into book (title, `desc`, cover_image) values ('City Below, The (Unter dir die Stadt)', 'reinvent distributed partnerships', 'http://dummyimage.com/217x100.png/dddddd/000000');
insert into book (title, `desc`, cover_image) values ('Fragile Trust: Plagiarism, Power, and Jayson Blair at the New York Times, A', 'brand user-centric models', 'http://dummyimage.com/181x100.png/cc0000/ffffff');
insert into book (title, `desc`, cover_image) values ('Strategy of the Snail, The (Estrategia del Caracol, La)', 'aggregate intuitive experiences', 'http://dummyimage.com/220x100.png/dddddd/000000');
insert into book (title, `desc`, cover_image) values ('Bullets Over Broadway', 'benchmark B2C initiatives', 'http://dummyimage.com/117x100.png/cc0000/ffffff');
insert into book (title, `desc`, cover_image) values ('Lonesome Dove', 'deploy leading-edge synergies', 'http://dummyimage.com/146x100.png/ff4444/ffffff');
insert into book (title, `desc`, cover_image) values ('Dragon Crusaders', 'harness real-time methodologies', 'http://dummyimage.com/165x100.png/cc0000/ffffff');
insert into book (title, `desc`, cover_image) values ('Taking Off', 'architect dot-com channels', 'http://dummyimage.com/165x100.png/dddddd/000000');
insert into book (title, `desc`, cover_image) values ('Harlan: In the Shadow of Jew Suess (Harlan - Im Schatten von Jud Süss)', 'cultivate holistic infomediaries', 'http://dummyimage.com/233x100.png/cc0000/ffffff');
insert into book (title, `desc`, cover_image) values ('High and Dizzy', 'integrate enterprise infrastructures', 'http://dummyimage.com/189x100.png/ff4444/ffffff');
insert into book (title, `desc`, cover_image) values ('Hollywood Shuffle', 'monetize virtual technologies', 'http://dummyimage.com/183x100.png/5fa2dd/ffffff');
insert into book (title, `desc`, cover_image) values ('Abe Lincoln in Illinois', 'harness enterprise content', 'http://dummyimage.com/244x100.png/dddddd/000000');
insert into book (title, `desc`, cover_image) values ('I Hate Valentine''s Day', 'seize collaborative deliverables', 'http://dummyimage.com/111x100.png/cc0000/ffffff');
insert into book (title, `desc`, cover_image) values ('My Brother Is an Only Child (Mio fratello è figlio unico)', 'recontextualize enterprise e-commerce', 'http://dummyimage.com/182x100.png/5fa2dd/ffffff');
